// Ví dụ dữ liệu quận/huyện cho một số thành phố lớn
export const DISTRICTS = {
  "Hồ Chí Minh": [
    "Quận 1",
    "Quận 2",
    "Quận 3",
    "Quận 4",
    "Quận 5",
    "Quận 6",
    "Quận 7",
    "Quận 8",
    "Quận 9",
    "Quận 10",
    "Quận 11",
    "Quận 12",
    "Bình Thạnh",
    "Gò Vấp",
    "Phú Nhuận",
    "Tân Bình",
    "Tân Phú",
    "Bình Tân",
    "Thủ Đức",
    "Bình Chánh",
    "Củ Chi",
    "Hóc Môn",
    "Nhà Bè",
    "Cần Giờ",
  ],
  "Hà Nội": [
    "Ba Đình",
    "Hoàn Kiếm",
    "Tây Hồ",
    "Long Biên",
    "Cầu Giấy",
    "Đống Đa",
    "Hai Bà Trưng",
    "Hoàng Mai",
    "Thanh Xuân",
    "Sóc Sơn",
    "Đông Anh",
    "Gia Lâm",
    "Nam Từ Liêm",
    "Thanh Trì",
    "Bắc Từ Liêm",
    "Mê Linh",
    "Hà Đông",
    "Sơn Tây",
    "Ba Vì",
    "Phúc Thọ",
    "Đan Phượng",
    "Hoài Đức",
    "Quốc Oai",
    "Thạch Thất",
    "Chương Mỹ",
    "Thanh Oai",
    "Thường Tín",
    "Phú Xuyên",
    "Ứng Hòa",
    "Mỹ Đức",
  ],
  // ...có thể bổ sung thêm các tỉnh/thành khác
};
